## Week 10 Challenge

### Importing necessary libraries

In [1]:
import numpy as np

**Q1** - *Create two numpy arrays. The first array, called arr1 should be of one dimension and consist of six elements of float type. The second array, called arr2 should be of two dimensions and each sub-array should consist of 5 elements of string type. Display these two numpy arrays.*

In [2]:
#Creating a one dimensional numpy array
arr1 = np.array([i for i in range(6)], dtype = 'float')

#Creating a two dimensional array with string elements -- Unicode
arr2 = np.array([['ac', 'b', 'c', 'd', 'e'], ['f', 'g', 'h', 'i','j']], dtype = 'U')

#Printing the two arrays
print('The one dimensional array: \n{}'.format(arr1))
print('\nThe two dimensional array: \n{}'.format(arr2))

The one dimensional array: 
[0. 1. 2. 3. 4. 5.]

The two dimensional array: 
[['ac' 'b' 'c' 'd' 'e']
 ['f' 'g' 'h' 'i' 'j']]


**Q2** - *For the arrays arr1 and arr2 created in Q.No.1, display the following properties: data type and dimensions. Reshape arr1 into a two dimensional array of 2 rows and three columns, and display the reshaped array. Similarly, reshape arr2 into a single dimensional array and display the reshaped array.*

In [3]:
#Displaying the properties of the two arrays created above
print('The data type of arr1: {}'.format(arr1.dtype))
print('The dimensions of arr1: {}'.format(arr1.shape))

print('\n' + '*' * 15 + '\n')
print('The data type of arr2: {}'.format(arr2.dtype))
print('The dimensions of arr2: {}\n'.format(arr2.shape))

print('\n' + '*' * 15 + '\n')
print('The reshaped arr1: \n{}'.format(arr1.reshape(2,3)))
print('\nThe reshaped arr2: \n{}'.format(arr2.reshape(-1)))

The data type of arr1: float64
The dimensions of arr1: (6,)

***************

The data type of arr2: <U2
The dimensions of arr2: (2, 5)


***************

The reshaped arr1: 
[[0. 1. 2.]
 [3. 4. 5.]]

The reshaped arr2: 
['ac' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']


**Q3** - *Create a two dimensional array called arr3, of 3 rows and 4 columns which is initialized to zeroes. Create another single dimensional array called arr4, with 6 elements and which is initialized to ones. The type of arr4 is int.*

In [4]:
#Creating a numpy zeros array (3,4) in size -- float type by default

arr3 = np.zeros((3,4))
print('Two dimensional arr3 initialized with zeros: \n{}'.format(arr3))

#Creating a numpy ones array 6 elements in size -- int type

arr4 = np.ones((6,), dtype = 'int')
print('\nOne dimensional arr4 initialized with ones: \n{}'.format(arr4))

Two dimensional arr3 initialized with zeros: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

One dimensional arr4 initialized with ones: 
[1 1 1 1 1 1]


**Q4** - *Create a list called list1 with the elements 10,20,30,40,50. Now, create a numpy array called arr5 from list1, using the method asarray. The data type of arr5 is float. Similarly, create another array called arr6, from list1, using the method fromiter, whose data type is int. Display arr5 and arr6.*

In [5]:
#Creating a numpy array from list

list1 = [num for num in range(10,60,10)]
arr5 = np.asarray(list1, dtype = 'float')
print('arr5 created from list1: \n{}'.format(arr5))

#Creating a numpy array from an iterable object list1 -- Displaying all values in list1
arr6 = np.fromiter(list1, dtype = 'int', count= -1) 
print('\narr6 created using fromiter method: \n{}'.format(arr6))

arr5 created from list1: 
[10. 20. 30. 40. 50.]

arr6 created using fromiter method: 
[10 20 30 40 50]


**Q5** - *Create a numpy array called arr7 using the method arange. The starting value of this array is 12 and ending value is 99, with a step size of 3. Use the linspace method to create another array called arr8, where the starting value is 12 and ending value is 99 and which contains 50 evenly spaced elements.*

In [6]:
#Creating a numpy array using arange method

arr7 = np.arange(12, 100, 3)
print('Creating numpy array using arange method: \n{}'.format(arr7))

#Using the linspace method to create a numpy array
arr8 = np.linspace(12, 99, 50)
print('\nCreating numpy array using linspace method: \n{}'.format(arr8))

Creating numpy array using arange method: 
[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]

Creating numpy array using linspace method: 
[12.         13.7755102  15.55102041 17.32653061 19.10204082 20.87755102
 22.65306122 24.42857143 26.20408163 27.97959184 29.75510204 31.53061224
 33.30612245 35.08163265 36.85714286 38.63265306 40.40816327 42.18367347
 43.95918367 45.73469388 47.51020408 49.28571429 51.06122449 52.83673469
 54.6122449  56.3877551  58.16326531 59.93877551 61.71428571 63.48979592
 65.26530612 67.04081633 68.81632653 70.59183673 72.36734694 74.14285714
 75.91836735 77.69387755 79.46938776 81.24489796 83.02040816 84.79591837
 86.57142857 88.34693878 90.12244898 91.89795918 93.67346939 95.44897959
 97.2244898  99.        ]


**Q6** - *In the array arr2 defined in Q.No. 1, what is the output of the following statements: print(arr2), print(arr2[0:1]), print(arr2[1][3]), print (arr2[1])*

In [7]:
#Printing results of arr2

print('Printing arr2: \n{}'.format(arr2))
print('\nPrinting the first row of arr2: \n{}'.format(arr2[0:1]))
print('\nPrinting the fourth element in the second row of arr2: \n{}'.format(arr2[1][3]))
print('\nPrinting the second row of arr2: \n{}'.format(arr2[1]))

Printing arr2: 
[['ac' 'b' 'c' 'd' 'e']
 ['f' 'g' 'h' 'i' 'j']]

Printing the first row of arr2: 
[['ac' 'b' 'c' 'd' 'e']]

Printing the fourth element in the second row of arr2: 
i

Printing the second row of arr2: 
['f' 'g' 'h' 'i' 'j']


**Q7** - *Create a two dimensional array called arr9 with the following elements: [101, 322, 768], [233, 124, 390], [534, 122, 216]. From arr9, create an array called arr10 which contains the elements 101, 322, 390, 122 using advanced integer indexing. Create another array called arr11 which contains elements of first and second rows, and second and third columns using slicing operations.*

In [8]:
arr9 = np.array([[101, 322, 768], [233, 124, 390], [534, 122, 216]])
print('Printing arr9: \n{}'.format(arr9))

#Using integer indexing methods to create arr10
arr10 = arr9[[0, 0, 1, 2], [0, 1, 2, 1]] 
print('\nObtaining arr10 using integer indexing: \n{}'.format(arr10))

#Creating arr11 using slicing operations
arr11 = arr9[:2, 1:]
print('\nObtaining arr11 using slicing operations: \n{}'.format(arr11))

Printing arr9: 
[[101 322 768]
 [233 124 390]
 [534 122 216]]

Obtaining arr10 using integer indexing: 
[101 322 390 122]

Obtaining arr11 using slicing operations: 
[[322 768]
 [124 390]]


**Q8** - *From array arr9 created in Q.No. 7, find all elements greater than 200 using boolean indexing, find all non-NaN elements, and find all non-float elements. Find the result of adding arrays arr9 and another array of 3 elements, using the concept of broadcasting.*

In [10]:
#Using boolean indexing
bool_arr1 = arr9[arr9 > 200]
print('All elements in arr9 greater than 200: \n{}'.format(bool_arr1))

#Finding all non-NaN elements
bool_arr2 = arr9[~np.isnan(arr9)]
print('\nAll elements in arr9 that are non-NaN elements: \n{}'.format(bool_arr2))

#Finding all non-float datatype elements
bool_arr3 = arr9[arr9.dtype != 'float']
print('\nAll elements in arr9 that are non-float elements: \n{}'.format(bool_arr3))

#Depicting the concept of broadcasting
#Creating an array of 3 elements

test_arr = np.array([num for num in range(10, 40, 10)])

print('\n' + '*' * 20 + '\n')
print('Printing arr9 for reference: \n{}'.format(arr9))
print('\nPrinting test_arr for reference: \n{}'.format(test_arr))
print('\nThe resulting of addition using broadcasting: \n{}'.format(arr9 + test_arr))

All elements in arr9 greater than 200: 
[322 768 233 390 534 216]

All elements in arr9 that are non-NaN elements: 
[101 322 768 233 124 390 534 122 216]

All elements in arr9 that are non-float elements: 
[[[101 322 768]
  [233 124 390]
  [534 122 216]]]

********************

Printing arr9 for reference: 
[[101 322 768]
 [233 124 390]
 [534 122 216]]

Printing test_arr for reference: 
[10 20 30]

The resulting of addition using broadcasting: 
[[111 342 798]
 [243 144 420]
 [544 142 246]]


**Q9** - *For the array arr9, find its transpose. Find the result of joining the arrays arr1 and arr4 along axis 0.*

In [12]:
#Finding the transpose of arr9
print('The transpose of arr9: \n{}'.format(arr9.T))

#Using concatenation to join two arrays along axis 0
print('\nPrinting arr1 for reference: \n{}'.format(arr1))
print('\nPrinting arr4 for reference: \n{}'.format(arr4))

#Concatenating the two 1D arrays along axis 0 -- in shape (size)
concat_arr1 = np.concatenate((arr1, arr4), axis = 0)
print('\nThe result of concatenation along axis 0 when both arrays are 1D: \n{}'.format(concat_arr1))

#Concatenating the two 1D arrays by reshaping them to be 2D row vectors of form -- (1, size)
concat_arr2 = np.concatenate((arr1.reshape(1, -1), arr4.reshape(1, -1)), axis = 0)
print('\nThe result of concatenation along axis 0 using reshape: \n{}'.format(concat_arr2))

The transpose of arr9: 
[[101 233 534]
 [322 124 122]
 [768 390 216]]

Printing arr1 for reference: 
[0. 1. 2. 3. 4. 5.]

Printing arr4 for reference: 
[1 1 1 1 1 1]

The result of concatenation along axis 0 when both arrays are 1D: 
[0. 1. 2. 3. 4. 5. 1. 1. 1. 1. 1. 1.]

The result of concatenation along axis 0 using reshape: 
[[0. 1. 2. 3. 4. 5.]
 [1. 1. 1. 1. 1. 1.]]


**Q10** - *Using any two 2-dimensional arrays, demonstrate the working of the methods, hstack, vstack, hsplit and vsplit.*

In [13]:
#Creating two 2D test arrays for demonstrating the above methods
test_arr1 = np.arange(16).reshape((4,4))
test_arr2 = np.arange(16,32).reshape((4,4))
print('The first test array: \n{}'.format(test_arr1))
print('\nThe second test array: \n{}'.format(test_arr2))

print('\n' + '*' * 15 + '\n') 

#Hstack method
arr_hstack = np.hstack((test_arr1, test_arr2))
print('The two arrays stacked horizontally: \n{}'.format(arr_hstack))

#Vstack method
arr_vstack = np.vstack((test_arr1, test_arr2))
print('\nThe two arrays stacked vertically: \n{}'.format(arr_vstack))

#hsplit method -- Splitting arr_hstack into 4 sub arrays
print('\nSplitting the hstack array into 4 sub arrays: \n{}'.format(np.hsplit(arr_hstack, 4)))

#vsplit method -- Splitting arr_vstack into 2 sub arrays
print('\nSplitting the vstack array into 2 sub arrays: \n{}'.format(np.vsplit(arr_vstack, 2)))

The first test array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

The second test array: 
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

***************

The two arrays stacked horizontally: 
[[ 0  1  2  3 16 17 18 19]
 [ 4  5  6  7 20 21 22 23]
 [ 8  9 10 11 24 25 26 27]
 [12 13 14 15 28 29 30 31]]

The two arrays stacked vertically: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

Splitting the hstack array into 4 sub arrays: 
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([[16, 17],
       [20, 21],
       [24, 25],
       [28, 29]]), array([[18, 19],
       [22, 23],
       [26, 27],
       [30, 31]])]

Splitting the vstack array into 2 sub arrays: 
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
  